#!/bin/ash

get_part_info() {
	local ONE_LINE ONE_PART ONE_TYPE ONE_LABEL ONE_UUID ONE_PUUID
	rm -r -f /tmp/disk
	[ -d /tmp/disk/linux ] || mkdir -p /tmp/disk/linux
	[ -d /tmp/disk/cd ] || mkdir -p /tmp/disk/cd
	[ -d /tmp/disk/other ] || mkdir -p /tmp/disk/other
	busybox blkid |
	while IFS='' read ONE_LINE; do
		[ "${ONE_LINE:5:4}" = "loop" ] && continue
		[ "${ONE_LINE:5:6}" = "mapper" ] && continue
		[ "${ONE_LINE:5:3}" = "dm-" ] && continue
		ONE_PART="${ONE_LINE%%:*}"; ONE_PART="${ONE_PART#/dev/}"
		ONE_TYPE="${ONE_LINE#* TYPE=\"}" #find TYPE or "/" if missing
		[ "${ONE_TYPE:0:1}" = "/" ] && ONE_TYPE="" || ONE_TYPE="${ONE_TYPE%%\"*}"
		[ "$ONE_TYPE" ] || continue
		[ "$ONE_TYPE" = "swap" ] && continue
		ONE_LABEL="${ONE_LINE#* LABEL=\"}" #find LABEL or "/" if missing
		[ "${ONE_LABEL:0:1}" = "/" ] && ONE_LABEL="" || ONE_LABEL="${ONE_LABEL%%\"*}"
		ONE_UUID="${ONE_LINE#* UUID=\"}" #find UUID or "/" if missing
		[ "${ONE_UUID:0:1}" = "/" ] && ONE_UUID="" || ONE_UUID="${ONE_UUID%%\"*}"
		case $ONE_TYPE in
				ext2|ext3|ext4|reiserfs|minix|f2fs|crypto_LUKS) TYPE_DIR='/linux' ;;
				iso9660|udf) TYPE_DIR='/cd' ;;
				*) TYPE_DIR='/other' ;;
		esac
		echo "$ONE_UUID,$ONE_LABEL:$ONE_TYPE" > "/tmp/disk${TYPE_DIR}/$ONE_PART"
	done
}

EXE_DIR="$(dirname $(readlink -f ${0}))"

if [ "$(file -Lb /bin/busybox | grep '64-bit')" ]; then
	YAD_EXE='yad64'
else
	YAD_EXE='yad32'
fi

[ -d /tmp/disk/linux ] || get_part_info

PARTS_DIR="/tmp/disk"
if [ "$(ls -1 $PARTS_DIR/linux)" = "" ]; then
	exec "$EXE_DIR/saveconfig_file"
elif [ "$(ls -1 $PARTS_DIR/other)" = "" ]; then
	exec "$EXE_DIR/saveconfig_part"
else
	ICON_FILE='/usr/share/pixmaps/puppy/floppy.svg'
	OTHER_ICON="$EXE_DIR/icons/other.png"
	LINUX_ICON="$EXE_DIR/icons/linux.png"
	$YAD_EXE --window-icon="$ICON_FILE" --center --borders=6 --height=80 --title "Saveconfig" --buttons-layout=center \
		--text "This dialog is currently provided for testing purposes.

Both Linux and non-Linux partitions were found. You can:
<span foreground='blue'>Other</span>
Choose a non-linux partition to contain a Linux partition file.
<span foreground='blue'>Linux</span>
Choose an existing real Linux partition to contain the Puppy save folder." \
		--button=gtk-cancel:1 --button=Other!${OTHER_ICON}:2 --button=Linux!${LINUX_ICON}:4
	STATUS=$?
	case $STATUS in
		1) exit 1 ;;
		2) exec "$EXE_DIR/saveconfig_file" ;;
		4) exec "$EXE_DIR/saveconfig_part" ;;
	esac
fi

exit

PARTS_DIR="/tmp/disk/linux"
PARTS_LIST="$(ls -1 $PARTS_DIR/)"
if [ "$PARTS_LIST" ];then
	exec "$EXE_DIR/saveconfig_part"
else
	exec "$EXE_DIR/saveconfig_file"
fi

exit
